/*
 * This file was generated by the Gradle 'init' task.
 */
dependencyResolutionManagement {
    repositories {
        maven("https://hub.spigotmc.org/nexus/content/groups/public/")
        mavenCentral {
            content { includeGroup("net.kyori") }
        }
    }
}

pluginManagement {
    includeBuild("build-logic")
}

rootProject.name = "FeatherChatParent"
include(":Api")
include(":Bukkit")
include(":FeatherChat")
