/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "featherchat"
include(":featherchat-bukkit")
include(":featherchat-api")
include(":featherchat-core")
project(":featherchat-bukkit").projectDir = file("bukkit")
project(":featherchat-api").projectDir = file("api")
project(":featherchat-core").projectDir = file("core")
