/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    compileOnly("org.yaml:snakeyaml:1.32")
    implementation("co.aikar:acf-core:0.5.0-SNAPSHOT")
    implementation("net.kyori:adventure-platform-api:4.1.2")
    implementation("net.kyori:adventure-text-minimessage:4.11.0")
    implementation("net.kyori:adventure-text-serializer-legacy:4.11.0")
    implementation(project(":Api"))
}

description = "featherchat-core"