/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("xyz.mauwh.java-conventions")
}

dependencies {
    implementation("co.aikar:acf-core:0.5.0-SNAPSHOT")
    implementation("org.yaml:snakeyaml:1.30")
    implementation("net.kyori:adventure-text-serializer-legacy:4.11.0")
    implementation(project(":Api"))
}

description = "featherchat-core"