/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    war
    kotlin("jvm") version ("1.7.10")
    id("xyz.mauwh.java-conventions")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("co.aikar:acf-core:0.5.0-SNAPSHOT")
    implementation("net.kyori:adventure-text-serializer-legacy:4.11.0")
    implementation("org.yaml:snakeyaml:1.30")
    providedCompile(project(":featherchat-api"))
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "17"
    }
}

description = "featherchat-core"
