/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("xyz.mauwh.java-conventions")
}

dependencies {
    implementation("net.kyori:adventure-platform-bukkit:4.1.2")
    implementation("co.aikar:acf-bukkit:0.5.0-SNAPSHOT")
    implementation(project(":featherchat-core"))
    implementation(project(":featherchat-api"))
    compileOnly("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
}

description = "featherchat-bukkit"
