/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    compileOnly("org.jetbrains:annotations:23.0.0")
    implementation("net.kyori:adventure-platform-api:4.1.2")
    implementation("net.kyori:adventure-api:4.11.0")
}

description = "featherchat-api"
